### PR TITLE
chore: Align to upstream changes

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
There were breaking changes for `che-theia` in upstream.
The PR aligns `che-theia` to upstream changes:
- adapt `che-theia` to the changes https://github.com/eclipse-theia/theia/commit/aa4fe4a0a872d59d8b1110f7524687ea9772ac9c
- adapt `che-theia` to https://github.com/eclipse-theia/theia/commit/f9c031120708e0b4c7ef4afe86210144062ebde8
- Install 'libsecret' as it's used by keytar that Theia depends on
- Update git built-in to the version that supports `FileDecoration` API
- Align Task Service to upstream changes: https://github.com/eclipse-theia/theia/commit/d563b6b94bc378ab3003bef3dbdccdde86a9b546
- Update `yarn.lock`. As result some versions were updated. 
For example, `@types/prettier` from `2.2.3` to `2.3.0`. Formatting changes in the PR is related to this update. 

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19866
https://github.com/eclipse/che/issues/19984

### How to test this PR?

- One of the breaking change was related to task system, so `Che` tasks as well as `Theia`/VS Code tasks should be tested, especially running tasks and displaying the corresponding output.
- Another breaking change was - `Che` workspace couldn't start at all, please see https://github.com/eclipse/che/issues/19984, so starting a workspace should be tested.
- Activating `Git` and `Github` extensions should be fixed, please see https://github.com/eclipse-che/che-theia/pull/1142#issuecomment-862577016

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
let's check with the `libsecret` installed

**Comment by azatsarynnyy** [comment]
Now, git built-in fails:
image

trying to update git built-in to 1.52.1 that should support `FileDecoration API` https://github.com/eclipse-theia/theia/pull/8911

**Comment by RomanNikitenko** [comment]
thank you, Artem, so much for your help and providing additional fixes to align `che-theia` to upstream changes!

**Comment by azatsarynnyy** [comment]
I'm checking the UBI image manually to verify that adding libsecret solves the start-up issue.

**Comment by benoitf** [comment]
@azatsarynnyy it should be covered by 
`Happy Path / happy-path (ubi8, next) (pull_request) Successful in 52m `

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy it should be covered by
> `Happy Path / happy-path (ubi8, next) (pull_request) Successful in 52m `

ahh.. sure, I forgot :man_facepalming: Thanks!
So, @RomanNikitenko it's ready for review, I believe.

**Review by azatsarynnyy — APPROVED** [review]

**Review by benoitf — APPROVED** [review]
image

tested tasks, git, github, etc and I didn't see issues

**Comment by benoitf** [comment]
@RomanNikitenko 7.32.0 being already tagged I think we're in a good shape to merge ?

**Comment by RomanNikitenko** [comment]
> @RomanNikitenko 7.32.0 being already tagged I think we're in a good shape to merge ?

yes, sure!
I just wanted to give more time for people if someone would like to test/review the changes...

**Comment by benoitf** [comment]
> yes, sure!
> I just wanted to give more time for people if someone would like to test/review the changes...

yes, no issue on that (or pressure to get it merge faster)
Just that when it's the start of a sprint I think we're more open to have some little breakages than at the end of the sprint :-)

**Comment by zWingz** [comment]
> image
> 
> tested tasks, git, github, etc and I didn't see issues

How do you test this PR ?
Build a che-theia docker image from PR and use it as `theia-editor` in devfile ?

**Comment by RomanNikitenko** [comment]
> How do you test this PR ?
Build a che-theia docker image from PR and use it as theia-editor in devfile ?

this is one of the possible options

but actually for testing a PR changes you don't need to build images - you could use `Try it` buttons
try_it

**Comment by RomanNikitenko** [comment]
it looks like `try it` buttons [are broken](https://github.com/eclipse/che/issues/20099) at the moment, but usually it's possible to start a workspace and test changes using the buttons...

**Comment by zWingz** [comment]
> > How do you test this PR ?
> > Build a che-theia docker image from PR and use it as theia-editor in devfile ?
> 
> this is one of the possible options
> 
> but actually for testing a PR changes you don't need to build images - you could use `Try it` buttons
> try_it

it is so cool. but it still build a `theia-ide@next` image ?
Won't this be overwritten by other `theia-ide@next` images?

**Comment by RomanNikitenko** [comment]
> Won't this be overwritten by other theia-ide@next images?

You can go to `Happy path tests DevFile` => the corresponding meta.yaml file to see what images are used for the current PR.
There is a unique version of `che-theia` image...

happy_path_devfile

**Comment by zWingz** [comment]
@RomanNikitenko thanks

**Pull request merged**
