### PR TITLE
feat(explorer): Display Welcome panel when there are no projects in a devfile

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### What does this PR do?
Displays `Welcome` panel for the `Explorer` view when there are no projects in a devfile

### Screenshot/screencast of this PR

welcome_panel

https://user-images.githubusercontent.com/5676062/123442491-989f5680-d5dd-11eb-8e3a-f31ba8d3f3e3.mp4

newFolder

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19645

### How to test this PR?

1. Start a workspace from a devfile without projects - you should see the `Welcome` panel with `Clone Repository` and `New Folder` buttons in the `Explorer` view.
2. Try to use the buttons.
3. Start a workspace with projects - you shouldn't see the`Welcome` panel. 

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Review by vzhukovs — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Review by azatsarynnyy — APPROVED** [review]
I've tested both Clone Repository and New Folder functionality.
Everything works as expected and it makes the UX much better. :+1:

**Pull request merged**
