### PR TITLE
fix(plugins): Change path to plugins index.json file

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
When Che is deployed in single-host mode, the plugin registry does not respect index.json file, where all the plugins are described.
For that case, it's better to read plugins.json file directly.

### Screenshot/screencast of this PR

Screenshot from 2021-06-22 17-44-11

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19955

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Comment by benoitf** [comment]
hello, is it related to a missing / at the end of the URL ?
for example 
https://che-eclipse-che.apps.cluster-91de.91de.sandbox1444.opentlc.com/plugin-registry/v3/plugins/ works
https://che-eclipse-che.apps.cluster-91de.91de.sandbox1444.opentlc.com/plugin-registry/v3/plugins redirect to dashboard

**Comment by benoitf** [comment]
my question is: should we not fix the URL just by appending a single `/` instead of specifying `/index.json` ?

**Comment by vitaliy-guliy** [comment]
> my question is: should we not fix the URL just by appending a single `/` instead of specifying `/index.json` ?

What if it's a custom registry (surge.sh, etc), that is running not under apache, where index.json is not configured as directory index?
Then getting of the index file will be impossible.

In our case we always generate index.json file https://github.com/eclipse-che/che-plugin-registry/blob/main/tools/build/src/meta-yaml/index-writer.ts#L44, why not to read it by explicit link?

**Comment by benoitf** [comment]
well, I would say index.json is an implementation detail of the plug-in registry
as it's "emulating REST API' with / I would say it's better to use 'REST' calls so even if index.json become index.foo or is totally removed we're still safe.

**Comment by vitaliy-guliy** [comment]
Reworked on adding only '/plugins/' at the end.

**Review by benoitf — APPROVED** [review]

**Comment by vitaliy-guliy** [comment]
But we also need to investigate a bit the apache server.
In single host mode it generates wrong redirect link.

If you try
```
curl -v https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/plugin-registry/v3/plugins
```

you will get
```
HTTP/1.1 301 Moved Permanently
location: http://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/v3/plugins/
```

Location URI does not contain `/plugin-registry` anymore.

**Comment by benoitf** [comment]
@vitaliy-guliy might be related to https://github.com/eclipse/che/issues/19995

**Comment by vitaliy-guliy** [comment]
[crw-ci-test --rebuild]

**Comment by dmytro-ndp** [comment]
@vitaliy-guliy: [recent execution of Happy path test](https://github.com/eclipse-che/che-theia/pull/1154#issuecomment-866804063) has failed because of known issue https://github.com/eclipse/che/issues/18034

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy: [recent execution of Happy path test](https://github.com/eclipse-che/che-theia/pull/1154#issuecomment-866804063) has failed because of known issue [eclipse/che#18034](https://github.com/eclipse/che/issues/18034)

Thanks for your comment.
Merging the PR as there is `Happy Path / happy-path (alpine, next) (pull_request)` passes.

**Pull request merged**
