### PR TITLE
Make Che Theia to rely on main endpoint type

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
This PR makes Che Theia rely on the main endpoint type instead of deprecated ide.
Ide is still respected since Che Server uses it.

### Screenshot/screencast of this PR
Screenshot_20210521_180917

### What issues does this PR fix or reference?
it's one piece of many for https://github.com/devfile/devworkspace-operator/issues/399

It should be merged in sync with https://github.com/devfile/devworkspace-operator/issues/399 and https://github.com/eclipse-che/che-plugin-registry/pull/963

### How to test this PR?
1. deploy Che with DevWorkspace enabled.
Note that custom plugin registry and DWO should be deployed from the referenced PRs.
2. Make sure that Theia works without issues, like from master branch.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by benoitf** [comment]
@sleshchenko what is happening when deploying it on che-server ? it doesn't require to provide an `ide` attribute ?

**Comment by sleshchenko** [comment]
> @sleshchenko what is happening when deploying it on che-server ? it doesn't require to provide an `ide` attribute ?

My understanding may be wrong but I expect that Che Theia uses devfile v2 based objects, and when it comes to Che Server, which still returns and use ide type, Che Theia converts v1 to v2 where we replace ide to main https://github.com/eclipse-che/che-theia/pull/1113/files#diff-e182f95e1f366a9f84cfd4d9a0ead394d07140eb9d21477b68f0709ab9b37747R98
Do I miss anything?

**Comment by benoitf** [comment]
@sleshchenko that's correct, at the beginning of the PR I saw only `ide` being replaced by `main`

**Comment by benoitf** [comment]
@sleshchenko please update the body of the PR

**Comment by sleshchenko** [comment]
@benoitf done, sorry for missing it after making PR ready to review.

I also verified that Che Workspace and DevWorkspace work with Theia image built for a happy path.
Note I used custom plugin registry and DWO form the referenced PRs.

**Comment by sleshchenko** [comment]
I think happy path tests here are supposed to fail since they depends on the plugin registry.

**Review by benoitf — APPROVED** [review]

**Pull request merged**
