### PR TITLE
Fix boottime failures on non root K8s environment

### LINKED ISSUE #281: Exception on the  non-root environment.
### Description

It looks the-theia can't access `/proc/net/tcp6` in the instance running as non-root.

### Reproduction Steps

1. Run as the non-root instance
2. Start workspace
3. Check logs from `che-theia` container.

**OS and version:**    

7.0.0-RC-2.0-SNAPSHOT

**Diagnostics:** 

```
root ERROR [hosted-plugin: 54] (node:54) UnhandledPromiseRejectionWarning: Error: Unable to execut
e the command cat /proc/net/tcp6: Error: Command failed: cat /proc/net/tcp6
cat: can't open '/proc/net/tcp6': No such file or directory

    at new CliError (/tmp/theia-unpacked/eclipse_che_ports_plugin.theia/lib/cli-error.js:32:28)
    at /tmp/theia-unpacked/eclipse_che_ports_plugin.theia/lib/command.js:69:40
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:597:12)
```

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

* Fixes boottime failures on non root K8s environment.
* Enables to use `sudo` on the vanilla and some K8s based environment.

### What issues does this PR fix or reference?

* related on #284 #292

### CODE REVIEW

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by monaka** [comment]
This PR will be a good improvement for vanilla K8s users who want to use `sudo`.
But I can't say this is a critical fix. So I set the target milestone to 7.1.0.

**Comment by benoitf** [comment]
hello, what is the status of this PR ?

**Comment by monaka** [comment]
@benoitf IMO, this is still required on the vanilla K8s.
But it is behind the current master branch. I'll update soon.

**Comment by azatsarynnyy** [comment]
[ci-build]

**Comment by azatsarynnyy** [comment]
Hello @monaka 
would you mind looking at the failed PR checks, if the changes are still actual?

**Comment by benoitf** [comment]
closing as not updated

**Comment by monaka** [comment]
[ci-build]

**Comment by benoitf** [comment]
this PR is not rebased

**Comment by monaka** [comment]
@benoitf Yes. So I moved the status to "draft" temporary. I'm going to recheck which patches should be merged.

**Pull request closed without merging**
