### PR TITLE
fix(digests): Use correct theia modules for 7.32.x

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
It's for 7.32.x branch
if build.include specify a sha1, package.json files should use this one (and not take the current one when branch was created)

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19866#issuecomment-864770078

### How to test this PR?
Build without this patch (node build is failing)
Build with this patch (node build is working)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

Change-Id: I486abd733c665b0bdc82c423f258afb7497398fc
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by tsmaeder** [comment]
@benoitf but we're building our production artifacts against the theia source that is checked out, not against published modules, so how is this relevant? Wouldn't the outcome be the same for any version number?

**Comment by benoitf** [comment]
@tsmaeder people doing the build of nodejs build will fail (as reported there: https://github.com/eclipse/che/issues/19866#issuecomment-864770078)

**Comment by benoitf** [comment]
@tsmaeder also some modules are published and the dependencies are incorrect as well.

**Review by RomanNikitenko — APPROVED** [review]
Tested the changes:
- the build of `7.32.x` is failing **without** these changes
- I have built the current branch **with** these changes successfully using yarn
- the build of images is successful (`./build.sh --dockerfile:Dockerfile.alpine`)
- I was able to start a workspace with these changes without any problems

**Pull request merged**
