### PR TITLE
build: Adapt Build System to upstream changes

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### What does this PR do?
Provides alignment to upstream changes related to Build System.

Please pay attention that `linkless build` and classic `che-in-che development` were broken before.
The problems are NOT related to the current changes.
 I created separate issues 2 weeks ago:
- https://github.com/eclipse/che/issues/20814
- https://github.com/eclipse/che/issues/20816

After resolving those issues it will be possible to check if additional alignment is required for `linkless build` and classic `che-in-che` development.

For the classic `che-in-che` development probably some changes related to `jest` will be required (AFAIK there is a conflict with upstream - it looks like `jest` brings some transitive dependencies which leads to errors at compilation step).

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20538

### How to test this PR?

The PR doesn't provide any additional functionality.
It makes sense to check that it's possible to build `che-theia` assembly.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)
- [ ] Optional Companion PR for updating the HappyPath tests is approved and ready to be merged

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
[crw-ci-test --rebuild]

**Comment by RomanNikitenko** [comment]
The tests failed due to new breaking changes in upstream

Screenshot 2021-11-01 at 18 04 15

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Comment by RomanNikitenko** [comment]
[crw-ci-test --rebuild]

**Comment by RomanNikitenko** [comment]
[crw-ci-test --rebuild]

**Comment by RomanNikitenko** [comment]
[crw-ci-test --rebuild]

**Review by benoitf — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Comment by RomanNikitenko** [comment]
For reviewers - within testing the PR changes I detected a problem related to resource-monitor plugin
Screenshot 2021-12-10 at 13 11 19

investigating...

**Comment by RomanNikitenko** [comment]
The problem related to activation of `resource-monitor-plugin` was fixed by commit above.

**Review by azatsarynnyy — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
Within testing the PR I detected that some commands (not all) are rendered incorrectly
image

investigating...

**Comment by benoitf** [comment]
@RomanNikitenko is it related to i18n ?

**Comment by RomanNikitenko** [comment]
> @RomanNikitenko is it related to i18n ?

I think it's related to https://github.com/eclipse-theia/theia/commit/4ba6752cd15274f7fa189f7f22b779ff46c1588f

**Pull request merged**
