### PR TITLE
Check path to be a file when reading certificates

### PR DESCRIPTION
**Pull request by vinokurig**
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

### What does this PR do?
Fixes a bug when the plugins view shows an empty list.

### What issues does this PR fix or reference?

https://issues.redhat.com/browse/CRW-1710

### How to test this PR?

1. Start a workspace from devfile:
```
apiVersion: 1.0.0
metadata:
  name: wksp-custom-tki1v
components:
  - type: cheEditor
    reference: '<link to the generated meta.yaml, will be available when the PR is opened>'
```
2. Open the `Plugins` view: `View => Plugins`
3. See: plugins list must be loaded.
### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Review by azatsarynnyy — APPROVED** [review]

**Review by vzhukovs — APPROVED** [review]

**Review by RomanNikitenko — APPROVED** [review]

**Comment by azatsarynnyy** [comment]
@vinokurig are you sure the failed HappyPath tests are not related to the PR changes?
On the previous PR it passed.

**Comment by vinokurig** [comment]
I'll try to rerun tests

**Comment by vinokurig** [comment]
[crw-ci-test]

**Comment by vinokurig** [comment]
Looks like it doesn't work when the PR is closed :)

**Comment by RomanNikitenko** [comment]
@vinokurig 
FYI 
> At the same time PR check doesn't work normally at the moment, because CRW Jenkins CI continues suffering from infrastrucure outage introduced a few days ago https://one.redhat.com/legacy/outages/list/details/606a7ab556897a049f735d2f .

**Comment by RomanNikitenko** [comment]
I have rerun jobs with happy path tests for the current PR, waiting...

**Comment by vinokurig** [comment]
Thanks @RomanNikitenko

**Comment by RomanNikitenko** [comment]
The tests have failed o the same step:

tests_failed

**Comment by RomanNikitenko** [comment]
Unfortunately all jobs have failed and the cause of the problem is the same, please see the screenshot above.

**Comment by vinokurig** [comment]
I don't think that my changes caused workspace start error, I've checked it locally several times. I propose to wait for the nightly tests against master.

**Comment by RomanNikitenko** [comment]
I have started the checks for all jobs in the test PR **without your changes** https://github.com/eclipse-che/che-theia/pull/1049

**Comment by vinokurig** [comment]
I've tried the latest `che-theia` image which contains my changes and it works ok:

**Comment by RomanNikitenko** [comment]
Maybe something wrong with Happy Path tests...

**Comment by vinokurig** [comment]
Let's wait for results of your draft PR, then I'll rise this question in the QE channel

**Comment by dmytro-ndp** [comment]
@vinokurig : about happy path tests failure https://github.com/eclipse-che/che-theia/pull/1072#issuecomment-816647701
Happy path tests from master branch are not compatible with Eclipse Che stable version, that is 7.28.0

**Comment by vinokurig** [comment]
So this is expected?

**Comment by dmytro-ndp** [comment]
Yes, it is.

**Comment by vinokurig** [comment]
OK, thanks.

**Pull request merged**
