### PR TITLE
chore(workspace-plugin): display additional confirmation before cloning a project

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Asks the user whether he trust the authors of the project.

Since che-theia does not work wit the latest upstream changes https://github.com/eclipse/che/issues/20366, it was temporary switched to specific commit. This change will be reverted before merge.
```
THEIA_COMMIT_SHA=863c7382d70cc4f74108a3563a92a66b47cb121a
```

### Screenshot/screencast of this PR

Screenshot from 2021-08-26 17-39-55

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20249

### How to test this PR?

- Go to the latest comment from `che-bot`, click `Try It` button.

- Create a workspace with the devfile
```
apiVersion: 1.0.0
metadata:
  name: java-minimal
projects:
  - name: web-java-spring-petclinic
    source:
      location: 'https://github.com/che-samples/java-spring-petclinic'
      type: git
components:
  - type: cheEditor
    alias: che-theia
    reference: https://gist.githubusercontent.com/vitaliy-guliy/0abd17e4418ef06dd8f0e155d6dc33c7/raw/8b498d37dba1a0c2a6a594fd0053ec7198789def/editor.meta.yaml
``` 

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Comment by vitaliy-guliy** [comment]
[crw-ci-test --rebuild]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by vitaliy-guliy** [comment]
[crw-ci-test]

**Review by vinokurig — APPROVED** [review]

**Comment by vitaliy-guliy** [comment]
[crw-ci-test]

**Comment by Ohrimenko1988** [comment]
The "Happy Path" test has been passed 
https://github.com/eclipse-che/che-theia/pull/1203#issuecomment-909415074 .

From the QE side looks well.

**Pull request merged**
