### PR TITLE
Make sure, that proxy-related environment variables are passed to git…

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Takes proxy-related environment variables from the main Che-Theia process and uses them when executing `git` / `ssh` / `curl` commands in `workspace-plugin`.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19242

### How to test this PR?

Just create a workspace with any Git project

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Comment by vitaliy-guliy** [comment]
[crw-ci-test --rebuild]

**Comment by vitaliy-guliy** [comment]
@tolusha could you test this PR if it's possible? We just need any verdict on this PR.

**Comment by tolusha** [comment]
@vitaliy-guliy 
sure, in progress. Give me some time.

**Comment by vitaliy-guliy** [comment]
[crw-ci-test --rebuild]

**Comment by vitaliy-guliy** [comment]
[crw-ci-test --rebuild]

**Comment by vitaliy-guliy** [comment]
Link with [CRW-1836](https://issues.redhat.com/browse/CRW-1836), as it depends on this PR

**Comment by ghatwala** [comment]
So for https://issues.redhat.com/browse/CRW-1836 , on my proxy based OCP power clusters (4.6+4.7 ) as was facing issues in running below  simple devfile  in CRW2.8 .
```
apiVersion: 1.0.0
metadata:
  name: xml-plugin-test
projects:
  - name: xml-plugin-test
    source:
      location: 'https://github.com/che-samples/web-nodejs-sample.git'
      type: git
      branch: che-qe-tests
components:
  - id: redhat/vscode-xml/latest
    type: chePlugin
```
So using this PR , created `che-theia` and `che-theia-endpoint-runtime-binary` images locally on my node ( since upstream does not have power supported  `quay.io/crw_pr` images. 
Thereafter using below below devfile tried to create a workspace on CRW2.8 dashboard .
```
apiVersion: 1.0.0
metadata:
  name: xml-plugin-test
projects:
  - name: xml-plugin-test
    source:
      location: 'https://github.com/che-samples/web-nodejs-sample.git'
      type: git
      branch: che-qe-tests
components:
  - type: cheEditor
    alias: che-theia
    reference: https://gist.githubusercontent.com/vitaliy-guliy/ae9ef3a9b4f5334f9bfda39c270c870b/raw/050eab24b7df330c09c7a437b5eec94d6dd4ff2f/editor.meta.yaml
    memoryLimit: 512Mi
  - id: redhat/vscode-xml/latest
    type: chePlugin
```
Now we no longer observe the issues seen in CRW-1836.
image

Also confirming that this deploying is via this commit - https://github.com/eclipse-che/che-theia/commit/961c6061
image

Thanks for this PR - @vitaliy-guliy.

Also since this change will go into master branch only , @nickboldt  - am guessing you'll need this change in https://github.com/eclipse-che/che-theia/tree/7.31.x too so that it's incorporated  downstream during CRW2.9 build productization  ? Is that a correct process to have this change downstream for CRW 2.9 ?

**Comment by vitaliy-guliy** [comment]
@ghatwala you gave an excellent feedback!! Thanks.

**Review by RomanNikitenko — APPROVED** [review]

**Comment by nickboldt** [comment]
Please backport to 7.30.x branch too, for inclusion in CRW 2.9.

**Comment by vitaliy-guliy** [comment]
[crw-ci-test --rebuild]

**Comment by svor** [comment]
since we already have 7.31.x shouldn't it be backported into that branch as well?

**Comment by nickboldt** [comment]
7.31.x isn't used for CRW, but if you want to back port this from 7.32 to 7.31.2, feel free. 7.32 will be out in 13 days, so it depends on how urgent this fix is ... one week to wait? or two?

**Pull request merged**
