### PR TITLE
Update link after switching from `master` to `main`

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Update link after switching from `master` to `main`.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20000

### How to test this PR?

`docker-build` jobs should pass.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by azatsarynnyy** [comment]
The HappyPath tests are failed due to the known problem https://www.eclipse.org/lists/che-dev/msg04194.html.
The change here is build-related only. All the build jobs are passed. So, merging.

**Comment by dmytro-ndp** [comment]
@azatsarynnyy:
> The HappyPath tests are failed due to the known problem https://www.eclipse.org/lists/che-dev/msg04194.html.
The change here is build-related only. All the build jobs are passed. So, merging.

Actually, Happy path PR check failed because of different problem: che-theia build failure:
https://github.com/eclipse-che/che-theia/pull/1149#issuecomment-864240613
```
[2021-06-18T19:45:16.485Z]   ● Test Extensions › should skip clonning if source is an existing folder (and not a git uri to clone) and use it as the clonedDir
[2021-06-18T19:45:16.485Z] 
[2021-06-18T19:45:16.485Z]     Command failed: git init -b main
[2021-06-18T19:45:16.485Z]     error: unknown switch `b'
[2021-06-18T19:45:16.485Z]     usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [directory]
[2021-06-18T19:45:16.485Z] 
[2021-06-18T19:45:16.485Z]         --template <template-directory>
[2021-06-18T19:45:16.485Z]                               directory from which templates will be used
[2021-06-18T19:45:16.485Z]         --bare                create a bare repository
[2021-06-18T19:45:16.485Z]         --shared[=<permissions>]
[2021-06-18T19:45:16.485Z]                               specify that the git repository is to be shared amongst several users
[2021-06-18T19:45:16.485Z]         -q, --quiet           be quiet
[2021-06-18T19:45:16.485Z]         --separate-git-dir <gitdir>
[2021-06-18T19:45:16.485Z]                               separate git dir from working tree
[2021-06-18T19:45:16.485Z] 
[2021-06-18T19:45:16.485Z]       76 |
[2021-06-18T19:45:16.485Z]       77 |     function initGit(cwd: string) {
[2021-06-18T19:45:16.485Z]     > 78 |         cp.execSync('git init -b main', { cwd });
[2021-06-18T19:45:16.485Z]          |            ^
[2021-06-18T19:45:16.485Z]       79 |         cp.execSync('git config --local user.name "test user"', { cwd });
[2021-06-18T19:45:16.485Z]       80 |         cp.execSync('git config --local user.email user@example.com', { cwd });
[2021-06-18T19:45:16.485Z]       81 |         cp.execSync(`git add ${cwd}`, { cwd });
[2021-06-18T19:45:16.485Z] 
[2021-06-18T19:45:16.485Z]       at initGit (tests/init-sources/init-sources.spec.ts:78:12)
[2021-06-18T19:45:16.485Z]       at tests/init-sources/init-sources.spec.ts:70:9
[2021-06-18T19:45:16.486Z]       at step (tests/init-sources/init-sources.spec.ts:42:23)
[2021-06-18T19:45:16.486Z]       at Object.next (tests/init-sources/init-sources.spec.ts:23:53)
[2021-06-18T19:45:16.486Z]       at fulfilled (tests/init-sources/init-sources.spec.ts:14:58)
[2021-06-18T19:45:16.486Z] 
[2021-06-18T19:45:16.486Z] PASS tests/command.spec.ts
[2021-06-18T19:45:16.752Z] PASS tests/cdn/boostrap.spec.ts
[2021-06-18T19:45:16.752Z] PASS tests/cli-error.spec.ts
[2021-06-18T19:45:16.752Z] PASS tests/link.spec.ts
[2021-06-18T19:45:16.752Z] PASS tests/cdn/webpack-loader.spec.ts
[2021-06-18T19:45:23.444Z] -------------------------|---------|----------|---------|---------|-----------------------------
[2021-06-18T19:45:23.444Z] File                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s           
[2021-06-18T19:45:23.444Z] -------------------------|---------|----------|---------|---------|-----------------------------
[2021-06-18T19:45:23.444Z] All files                |   77.59 |    69.16 |   80.52 |   77.76 |                             
[2021-06-18T19:45:23.445Z]  src                     |   73.94 |    57.58 |   77.52 |   73.82 |                             
[2021-06-18T19:45:23.445Z]   cdn.ts                 |     100 |      100 |     100 |     100 |                             
[2021-06-18T19:45:23.445Z]   clean.ts               |     100 |       75 |     100 |     100 | 45                          
[2021-06-18T19:45:23.445Z]   cli-error.ts           |     100 |       50 |     100 |     100 | 17                          
[2021-06-18T19:45:23.445Z]   command.ts             |     100 |      100 |     100 |     100 |                             
[2021-06-18T19:45:23.445Z]   generate-assembly.ts   |   50.91 |    14.29 |      40 |      54 | 39-74                       
[2021-06-18T19:45:23.445Z]   index.ts               |       0 |      100 |     100 |       0 | 12-14                       
[2021-06-18T19:45:23.445Z]   init-sources.ts        |   93.64 |    84.21 |     100 |   93.25 | 134,164-167,294-300,323-326 
[2021-06-18T19:45:23.445Z]   init.ts                |   42.35 |    18.52 |   33.33 |   42.65 | 54-100,104-110,115-118      
[2021-06-18T19:45:23.445Z]   json-utils.ts          |   23.08 |        0 |       0 |      25 | 20-23,28-33                 
[2021-06-18T19:45:23.445Z]   link.ts                |   97.06 |     62.5 |     100 |    96.3 | 52                          
[2021-06-18T19:45:23.445Z]   logger.ts              |     100 |      100 |     100 |     100 |                             
[2021-06-18T19:45:23.445Z]   production.ts          |     100 |      100 |     100 |     100 |                             
[2021-06-18T19:45:23.445Z]   repository.ts          |     100 |       80 |     100 |     100 | 50,58                       
[2021-06-18T19:45:23.445Z]   update-dependencies.ts |       0 |        0 |       0 |       0 | 16-83                       
[2021-06-18T19:45:23.445Z]   yargs.ts               |       0 |        0 |       0 |       0 | 11-142                      
[2021-06-18T19:45:23.445Z]   yarn.ts                |   92.39 |    80.65 |    87.5 |   95.06 | 215-217,224-225             
[2021-06-18T19:45:23.445Z]  src/cdn                 |   95.45 |      100 |      96 |   95.27 |                             
[2021-06-18T19:45:23.445Z]   base.ts                |   96.77 |      100 |     100 |   96.55 | 97-98                       
[2021-06-18T19:45:23.445Z]   bootstrap.ts           |     100 |      100 |     100 |     100 |                             
[2021-06-18T19:45:23.445Z]   html-template.ts       |     100 |      100 |     100 |     100 |                             
[2021-06-18T19:45:23.445Z]   webpack-customizer.ts  |     100 |      100 |     100 |     100 |                             
[2021-06-18T19:45:23.445Z]   webpack-loader.ts      |     100 |      100 |     100 |     100 |                             
[2021-06-18T19:45:23.445Z]   webpack.config.ts      |       0 |      100 |       0 |       0 | 11-19                       
[2021-06-18T19:45:23.445Z] -------------------------|---------|----------|---------|---------|-----------------------------
[2021-06-18T19:45:23.445Z] 
[2021-06-18T19:45:23.445Z] Test Suites: 1 failed, 15 passed, 16 total
[2021-06-18T19:45:23.445Z] Tests:       13 failed, 60 passed, 73 total
[2021-06-18T19:45:23.445Z] Snapshots:   0 total
[2021-06-18T19:45:23.445Z] Time:        16.849 s
[2021-06-18T19:45:23.445Z] Ran all test suites.
[2021-06-18T19:45:23.445Z] Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
[2021-06-18T19:45:23.445Z] error Command failed with exit code 1.
[2021-06-18T19:45:23.445Z] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[2021-06-18T19:45:23.445Z] error Command failed with exit code 1.
[2021-06-18T19:45:23.445Z] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[2021-06-18T19:45:23.445Z] error Command failed with exit code 1.
[2021-06-18T19:45:23.445Z] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[2021-06-18T19:45:23.445Z] Copying Che-Theia generator
[2021-06-18T19:45:23.445Z] cp: cannot stat ‘/mnt/hudson_workspace/workspace/Che/e2e/minikube/pr-check/che-theia-pr-check/che-theia/dockerfiles/theia-dev/../../generator/eclipse-che-theia-generator.tgz’: No such file or directory
```

**Comment by azatsarynnyy** [comment]
Thanks @dmytro-ndp!
Note, Git version, used in HappyPath test, should be updated to 2.28, at least. To recognize `-b` argument in `git init -b main` command that is used in unit tests now.

```
Command failed: git init -b main
[2021-06-18T19:45:16.485Z]     error: unknown switch `b'
```

**Comment by benoitf** [comment]
maybe we could do `git init` and then `git checkout -b` to avoid to upgrade git in jobs ?

**Comment by azatsarynnyy** [comment]
> maybe we could do `git init` and then `git checkout -b` to avoid to upgrade git in jobs ?

sure, we could do that, as an alternative approach, if it won't be possible to update git

**Comment by azatsarynnyy** [comment]
I've prepared a PR that will allow continuing to use git < 2.28 for HappyPath tests.
https://github.com/eclipse-che/che-theia/pull/1150
Feel free to merge it if it will be needed.

**Pull request merged**
