### PR TITLE
chore: CRW-1995 backport from main - add...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: CRW-1995 backport from main - add libsecret rpm to theia ub8 runtime-install-dependencies

Change-Id: I5e226b1fd61fd53ace6691806b15f711f433bd32
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by RomanNikitenko — COMMENTED** [review]
should we provide the same changes for `alpine`?

**Comment by nickboldt** [comment]
> should we provide the same changes for `alpine`?

already there in https://github.com/eclipse-che/che-theia/blob/main/dockerfiles/theia/docker/alpine/runtime-install-dependencies.dockerfile#L11

**Comment by RomanNikitenko** [comment]
> > should we provide the same changes for `alpine`?
> 
> already there in https://github.com/eclipse-che/che-theia/blob/main/dockerfiles/theia/docker/alpine/runtime-install-dependencies.dockerfile#L11

your reference is for the `main` branch
the current changes are for `7.32.x`branch

**Comment by nickboldt** [comment]
> the current changes are for 7.32.xbranch

Yes. For CRW we use the 7.32.x branch. For Che, the 7.32.x branch is essentially EOL since 7.33.x now exists. So there's no reason to backport a change that will only be used by Che processes.

**Review by RomanNikitenko — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
> > the current changes are for 7.32.xbranch
> 
> Yes. For CRW we use the 7.32.x branch. For Che, the 7.32.x branch is essentially EOL since 7.33.x now exists. So there's no reason to backport a change that will only be used by Che processes.

I don't know if/how users use `7.32.x`branch (build own assembly based on 7.32?) that's why asked about the same change for `alpine`...

**Comment by nickboldt** [comment]
image

**Pull request merged**
