### PR TITLE
fix(convert): When converting devfile v1 to v2, registryUrl attribute is forgotten

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Devfile v1 is converted internally to devfile V2 to expose new API to plug-ins/extensions but `registryUrl` field was not handled.
Thus, if the editor needs to write the file at some point, this information is removed

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/19829

### How to test this PR?
Look at the unit test (now the field is preserved)

Another manual way : Add a custom component using `registryUrl` field, then starts the workspace, install another plug-in and now look at the updated devfile. New plug-in should be there but also the `registryUrl` should be still there

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

Change-Id: Ia7dd9aec31f0c6b5326c4d645bfbf4f87ac8e69e
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]

**Review by azatsarynnyy — APPROVED** [review]

**Comment by ibuziuk** [comment]
would be great to back port it for 7.30.x so that it would land in the 2.9 version of product

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
Happy path worked on ubi8 next

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Pull request merged**
