### PR TITLE
build: Fix build of Che-Theia and ci jobs for happy path tests

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### What does this PR do?
- There are breaking changes in upstream after merging the changes related to upgrade `Monaco` version.
The current PR pins `Che-Theia` to upstream `Theia` before the breaking changes.
- use 1.21.0 version of minikube for happy path tests

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20069
https://github.com/eclipse/che/issues/20076

### How to test this PR?

The build should pass successfully.
The tests should be happy.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Review by benoitf — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
[crw-ci-test --rebuild]

**Comment by RomanNikitenko** [comment]
[crw-ci-test --rebuild]

**Comment by RomanNikitenko** [comment]
[crw-ci-test --rebuild]

**Comment by RomanNikitenko** [comment]
[crw-ci-test --rebuild]

**Comment by RomanNikitenko** [comment]
[crw-ci-test --rebuild]

**Comment by RomanNikitenko** [comment]
depends on https://github.com/eclipse/che/issues/20076

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Review by benoitf — APPROVED** [review]

**Pull request merged**
