### PR TITLE
Remove usages of deprecated `Command.id` Theia API.

### PR DESCRIPTION
**Pull request by tsmaeder**
### Screenshot/screencast of this PR
Fixes the commands in the "my workspace" sidebar panel by using `Command.command` instead of the deprecated `Command.id`.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19441

### How to test this PR?
Click on anything that has a underlying command in the "my workspace" sidebar panel (open terminal, execute command)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by ericwill** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
Hello, there are other places in che-theia where `command.id` is used. While `.id` is deprecated it should still work from upstream theia. If you plan to only fix che-theia, then all occurrences of `command.id` need to be updated in che-theia.

**Comment by tsmaeder** [comment]
@benoitf I don't see any other places in che-theia. Anyway...there is no point in waiting to merge this PR: it's fixing a blocker problem.

**Comment by sunix** [comment]
is the description correct? replace `Command.command` with `Command.command`?
or `Command.id`?

**Comment by tsmaeder** [comment]
@sunix that would not be a very interesting PR ;-) `Command.command` is what should be used.

**Review by benoitf — APPROVED** [review]
This PR fixes the problem for container plug-in. I'm still not sure if we're missing other potential issues across all plug-ins/codebase that may still be using `id` (maybe if we detect that `id` is used we could add a warn in console.log as well)

@tsmaeder please update the title of the PR as we're now using PR title in changelog so I'm pretty sure nobody will understand what it means (semantic/conventional commit would be a good option there)

**Comment by tsmaeder** [comment]
[crw-ci-test --rebuild]

**Review by svor — APPROVED** [review]
- Tested commands and open terminal action in My Workspace view, everything works good.
- Tested `preLaunchTask` in debug configuration - works good
screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 03 30-12_54_50

**Pull request merged**
