### PR TITLE
fix(devfile): Handle cheEditor component in addition to chePlugin

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
when converting devfile to v2, cheEditor component was missing

there was an erroneous empty object when converting v1-->v2-->v1
### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19623

### How to test this PR?
Look at the test

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

Change-Id: If09e25de1a9dd3e62e11b7bbd73c8d4d10541d19
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
@svor @vitaliy-guliy you can close, amend, do anything with this PR

**Comment by ericwill** [comment]
@svor @vitaliy-guliy what are we doing with this PR? We need to fix the CRW blocker (https://github.com/eclipse/che/issues/19623) ASAP so if this PR fixes it let's go with that.

**Review by svor — APPROVED** [review]

**Comment by ericwill** [comment]
[crw-ci-test --rebuild]

**Comment by svor** [comment]
replaced by https://github.com/eclipse-che/che-theia/pull/1084

**Pull request closed without merging**
