### PR TITLE
feat(generator): support ssh protocol to clone repository

### PR DESCRIPTION
**Pull request by zWingz**
Signed-off-by: zwingz <zhengzwing@gmail.com>

### What does this PR do?

support ssh protocol to clone repository

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/20139

### How to test this PR?
```
che-init --alias https://github.com/eclipse-che/che-theia\=git@github.com/eclipse-che/che-thiea.git
```

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Comment by zWingz** [comment]
Whether this error is caused by the code I modified

**Comment by RomanNikitenko** [comment]
[crw-ci-test --rebuild]

**Comment by RomanNikitenko** [comment]
I restarted all happy path checks, waiting for the results...

**Review by azatsarynnyy — APPROVED** [review]
Thank you @zWingz for the contribution!

**Pull request closed without merging**
