### PR TITLE
chore: Pin che-theia to the upstream Theia commit

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### What does this PR do?
Pin `che-theia` to the upstream `Theia` commit before breaking changes.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20366

### How to test this PR?

There are 2 breaking changes in the upstream:
- starting a workspace fails, please see more details in the issue: https://github.com/eclipse/che/issues/20366
- activation of extensions fails (`Language Support for Java(TM) by Red Hat` and `Debugger for Java`):
extensions_activation

So, starting a workspace, the editor and activation of the extensions should be checked with these changes.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Review by azatsarynnyy — APPROVED** [review]

**Comment by azatsarynnyy** [comment]
So, is it ready to merge?

**Comment by vitaliy-guliy** [comment]
Please ensure, that java plugin is working properly
https://github.com/eclipse/che/issues/20360

**Comment by RomanNikitenko** [comment]
With these changes I started a workspace successfully 
Screenshot 2021-08-31 at 18 09 53

The devfile is:
```
apiVersion: 1.0.0
metadata:
  name: minimal-workspace
projects:
  - name: web-java-spring-petclinic
    source:
      location: 'https://github.com/che-samples/java-spring-petclinic'
      type: git
components:
  - type: cheEditor
    reference: 'https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1205/simple/che-theia-editor.yaml'
  - id: redhat/java8/latest
    type: chePlugin
```
So, I'm going to merge the PR ASAP

**Comment by RomanNikitenko** [comment]
> Let's use the same commit, as it used in che-theia 7.35.1 https://github.com/eclipse-che/che-theia/blob/7.35.1/build.include#L17
> You are referring to a commit, that is one day older.

are you sure about that?

**Comment by vitaliy-guliy** [comment]
> > You are referring to a commit, that is one day older.
> 
> are you sure about that?

You are right. A commit, that I mentioned, is already 13 days old.

**Pull request merged**
