### PR TITLE
feat(recommendation-plugin): do not use axios anymore from the plug-in but use CheTheia service

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Links can use some self-signed certificates and then axios should be configured to do that.
Instead of handling that in every plug-in, delegate to a common service.

### What issues does this PR fix or reference?
fix https://issues.redhat.com/browse/CRW-1702

### How to test this PR?
First, check that recommendation plug-in is still working as expected.
Then, we can assume the common service works as expected in case of proxy and self-signed certificates with https :-)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Comment by nickboldt** [comment]
will this be cherrypicked to 7.32.x? or only fixed in 7.33?

**Comment by benoitf** [comment]
cherry-picked once it's merged (as long with the previous PR)

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Review by svor — APPROVED** [review]
Tested on local minikube instance. 
As a result two already registered issues were detected:
-  https://github.com/eclipse/che/issues/19883
- https://github.com/eclipse/che/issues/19751

but in case of current changes, recommendation plugin works as before vscode-xml plugin was recommended to install and it was installed successfully.

screenshot-che-eclipse-che 172 17 0 2 nip io-2021 06 18-12_14_21

**Comment by benoitf** [comment]
@svor thanks for the test.
I somehow missed https://github.com/eclipse/che/issues/19883, will look at it

**Pull request merged**
