### PR TITLE
chore: Move vsix download code to endpoint runtime binary

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
Move vsix download related code from vsix-installer image to endpoint runtime binary image.

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-1731

### How to test this PR?
Start minikube instance using CR-patch:
```yaml
spec:
  devWorkspace:
    enabled: true
  server:
    dashboardImage: 'quay.io/eclipse/che-dashboard:next'
    dashboardImagePullPolicy: Always
    customCheProperties:
      # CHE_DEBUG_SERVER: "true"
      CHE_INFRA_KUBERNETES_ENABLE__UNSUPPORTED__K8S: "true"
  k8s:
    singleHostExposureType: 'gateway'
```
using the following command:
```bash
$ ./run server:deploy --installer=operator --workspace-engine=dev-workspace --platform=minikube --che-operator-cr-patch-yaml=che-custom-che-server.yaml
```

Test repository with modified `theia-endpoint-runtime-binary`: https://github.com/vzhukovs/che-editor-test2

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)
- [ ] Optional Companion PR for updating the HappyPath tests is approved and ready to be merged

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by azatsarynnyy — COMMENTED** [review]
When starting a workspace with the following factory link
https://192.168.39.105.nip.io/#https://github.com/vzhukovs/che-editor-test2
I see in the dashboard:
```
Initializing DevWorkspace

Error provisioning storage: Could not rewrite container volume mounts: container 'tools' references undefined volume 'remote-endpoint'
```

**Comment by vzhukovs** [comment]
> When starting a workspace with the following factory link
> https://192.168.39.105.nip.io/#https://github.com/vzhukovs/che-editor-test2
> I see in the dashboard:
> 
> ```
> Initializing DevWorkspace
> 
> Error provisioning storage: Could not rewrite container volume mounts: container 'tools' references undefined volume 'remote-endpoint'
> ```

Try to restart the workspace, there's something with the dashboard. Because the devfile is the identically the same as Dasboard provides for java spring boot stack.

**Review by azatsarynnyy — COMMENTED** [review]
After restarting the workspace, I see the extensions from `che-theia.eclipse.org/vscode-extensions` attribute are installed.

**Review by azatsarynnyy — COMMENTED** [review]
docker build job has failed with `bash: /home/runner/work/che-theia/che-theia/dockerfiles/theia-vsix-installer/build.sh: No such file or directory`

**Comment by vzhukovs** [comment]
> docker build job has failed with `bash: /home/runner/work/che-theia/che-theia/dockerfiles/theia-vsix-installer/build.sh: No such file or directory`

Checking that

**Review by azatsarynnyy — APPROVED** [review]
All the required PR checks are green. Several HappyPath checks are passed. So, approving.

**Review by benoitf — APPROVED** [review]
it looks ok 👍

**Pull request merged**
