### PR TITLE
chore: Rename next build job. Send notification of its failure to mattermost

### PR DESCRIPTION
**Pull request by mkuznyetsov**
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>

### What does this PR do?
Rename CI build job to next-build.yaml (To make it similar with other next build jobs in Eclipse Che projects)
Add notification that will be sent to Eclipse MM channel

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by azatsarynnyy — APPROVED** [review]
Nice improvement. Thanks!

**Comment by vitaliy-guliy** [comment]
I suppose happy-path test are failing because of https://github.com/eclipse/che/pull/20374 is not merged yet.
To merge that PR we need to have published `che-theia:next` to be sure tests are passed.

**Comment by RomanNikitenko** [comment]
> I suppose happy-path test are failing because of [eclipse/che#20374](https://github.com/eclipse/che/pull/20374) is not merged yet.
> To merge that PR we need to have published `che-theia:next` to be sure tests are passed.

@vitaliy-guliy 
I see that https://github.com/eclipse/che/pull/20374 is not ready to merge.

So:
- https://github.com/eclipse-che/che-theia/pull/1203 was merged
- but adaptation for happy path tests (https://github.com/eclipse/che/pull/20374) was rejected

I would say it's better to have both PRs approved first and only then merge.

**Comment by vitaliy-guliy** [comment]
[crw-ci-test]

**Review by azatsarynnyy — COMMENTED** [review]
@mkuznyetsov now, it's good to merge

**Pull request merged**
