### PR TITLE
fix: Initialize '_hostPattern' in mini-browser environment

### PR DESCRIPTION
**Pull request by Bolodya1997**
### What does this PR do?
Initializes `this._hostPattern` in `CheMiniBrowserEnvironment` `postConstruct()` to enable mini-browser.

### Screenshot/screencast of this PR
image

### What issues does this PR fix or reference?
Closes https://github.com/eclipse/che/issues/21510.

### How to test this PR?
1. Create sample workspace.
2. Create `aaa.html` file.
3. Type `aaaaa`.
4. Click on Open Preview.
5. Tab with HTMP preview is opened to the right side.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)
- [ ] Optional Companion PR for updating the HappyPath tests is approved and ready to be merged

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by Bolodya1997** [comment]
I'm still failing to pass `eclipsefdn/eca` check even with the signed commit and signed ECA:
image

**Comment by benoitf** [comment]
@Bolodya1997 you need to make sure that ECA is valid

Are you an Eclipse member ? are you using the same email address ?

**Comment by Bolodya1997** [comment]
@benoitf 
I suppose there was a problem with different email set in GitHub settings, now ECA is valid.

**Review by benoitf — APPROVED** [review]
Tried with https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2?che-editor=https://gist.githubusercontent.com/benoitf/65cb7135fdeff9ea97cdaf58c4dd75e4/raw/e5d2afca42060d43b91b3c525ce64b0c52b1986b/theia-minibrowser.yaml

image

image



thanks @Bolodya1997 !

**Comment by Divine1** [comment]
@Bolodya1997 @benoitf  when will  this fix get  released for users?

**Pull request merged**
