### PR TITLE
chore: should be able to uninstall plugins if che-theia-plugins.yaml is inlined in the devfile

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com.com>

### What does this PR do?
- If `.che/che-theia-plugins.yaml` file is inlined in the devfile, all the plugins will be marked as installed. Does the same when the devfile contains `.vscode/extensions.json`.
- For devworkspaces, switches to using `che-theia-plugin.yaml` instead of `meta.yaml`.

### Screenshot/screencast of this PR

Screenshot from 2022-07-19 17-54-48

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/21423

### How to test this PR?

To test the behavior with inlined `che-theia-plugins.yaml` create workspace with a factory
`che-url#https://github.com/vitaliy-guliy/web-nodejs-sample/tree/inlined-che-theia-plugins-yaml?che-editor=https://gist.githubusercontent.com/vitaliy-guliy/bc6ff64a716a30bfc7492cec9314f3cf/raw/abcfeff8ccc9a1992fa9a6d4fe7a7a558dc7b7df/editor.meta.yaml`
 
To test the behavior with inlined `extensions.json` use
`che-url#https://github.com/vitaliy-guliy/web-nodejs-sample/tree/che-qe-extensions-test?che-editor=https://gist.githubusercontent.com/vitaliy-guliy/bc6ff64a716a30bfc7492cec9314f3cf/raw/abcfeff8ccc9a1992fa9a6d4fe7a7a558dc7b7df/editor.meta.yaml`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)
- [ ] Optional Companion PR for updating the HappyPath tests is approved and ready to be merged

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by svor — APPROVED** [review]
Tested on dogfooding instance, all plugins were installed and it's possible to install/unisntall plugins during the work
screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 07 21-14_00_34

screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 07 21-13_32_00

**Comment by svor** [comment]
@azatsarynnyy @benoitf are you going to review this PR or we can merge it?

**Comment by benoitf** [comment]
@svor you can merge

**Comment by svor** [comment]
Thanks!

**Comment by nickboldt** [comment]
Building from main in https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/theia-sources_3.x/15/ (previous build died on s390x)

**Pull request merged**
